title: My Page
email: wvicente@gmail.com

description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
host: 0.0.0.0
url: "" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  wvicente

markdown: kramdown
plugins:
  - jekyll-feed
